### ISSUE TITLE
Clarification on the license of the template

### ISSUE THREAD

**Issue by daadu** [studiolumina/naid#1]
Hello,

The template is wonderful, and I am considering using it for my personal project - the repo has no license file - can you clarify the license and terms of usage? I think that would make it clear for other as well.

**Comment by gingerchew** [comment]
Sure thing! I just added the MIT license, not sure what you mean by terms of usage?

**Comment by daadu** [comment]
MIT License clarifies the terms of usage, no additional info required. Thanks for quick update.
